-- Analytics views are managed by backend/src/services/postgres.service.ts.
-- The backend recreates them on every application startup to keep existing
-- pgdata volumes aligned with the current semantic layer.
